### ISSUE TITLE
Reduce memory overhead

### ISSUE THREAD

**Issue by conwandy** [conwandy/VIO#2]
Code runs slow, make it faster by using itertuples.

**Comment by conwandy** [comment]
`speed_breakout_route = {
    '4 SPEEDS': [4, 'AUTO_4_SPEED_PCT'],
    '5 SPEEDS': [5, 'AUTO_5_SPEED_PCT'],
    '6 SPEEDS': [6, 'AUTO_6_SPEED_PCT'],
    '6_7 SPEEDS': [6, 'AUTO_6_7_SPEED_PCT'],
    '8 SPEEDS': [8, 'AUTO_8_SPEED_PCT'],
    '7_8 SPEEDS': [8, 'AUTO_7_8_SPEED_PCT'],
    '10 SPEEDS': [10, 'AUTO_10_SPEED_PCT'],
    'CVTs': ['CVT', 'CVT_PCT']
}


def get_speed_breakout_df(df, speed_route, vio_year):
    duplicated_rows = pd.DataFrame(columns=df.columns)
    for row in df.itertuples(index=False):
        print(row)
        for key, value in speed_route.items():
            if getattr(row, key) > 0:
                num_speeds = value[0]
                speed_pct_header = value[1]
                new_row = get_speed_breakout_row(row, num_speeds, speed_pct_header, vio_year)
                duplicated_rows = pd.concat([duplicated_rows, new_row.to_frame().T], ignore_index=True)
    return duplicated_rows`

**Comment by conwandy** [comment]
Pandas(_0=2017, _1='RWD', LITERS=6.0, _3=141007.0, AUTO_4_SPEED_PCT=0.0, AUTO_5_SPEED_PCT=0.0, AUTO_6_SPEED_PCT=1.0, AUTO_6_7_SPEED_PCT=0.0, AUTO_7_8_SPEED_PCT=0.0, AUTO_8_SPEED_PCT=0.0, AUTO_10_SPEED_PCT=0.0, CVT_PCT=0.0, TOTAL=6, _13='2022', Key='141007.6.0.RWD', _15=0, _16=0, _17=6, _18=0, _19=0, _20=0, _21=0, CVTs=0)
Traceback (most recent call last):
  File "C:\Users\aconway\PycharmProjects\pythonProject\vio\vio_test.py", line 108, in <module>
    speed_breakout_df = get_speed_breakout_df(df, speed_breakout_route, file_year)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aconway\PycharmProjects\pythonProject\vio\vio_test.py", line 100, in get_speed_breakout_df
    if getattr(row, key) > 0:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'Pandas' object has no attribute '4 SPEEDS'

**Comment by conwandy** [comment]
@n5d4, Regarding the column names with the '_' prefix above. I understand these are automatically generated by Pandas when using the itertuples() method. Having a little trouble with this one.

**Comment by n5d4** [comment]
Try accessing the item in the row by position rather than name.
